import type { Race, StatCard, RadioClip, Quote, TierLevel, Product, TriviaQuestion } from "@/types";

export const CAREER_STATS: StatCard[] = [
  { value: "35", unit: "+", label: "Grand Prix Wins" },
  { value: "103", unit: "+", label: "Podium Finishes" },
  { value: "1", unit: "st", label: "Monaco GP Victory" },
  { value: "77", unit: "+", label: "Pole Positions" },
  { value: "1", unit: "×", label: "F2 Champion" },
  { value: "2024", unit: "", label: "World Champion", isGold: true },
];

export const FEATURED_RACES: Race[] = [
  {
    id: "bahrain-2019",
    season: 2019,
    round: 2,
    circuit: "Bahrain Grand Prix",
    country: "Bahrain",
    flag: "🇧🇭",
    date: "31 March 2019",
    result: "P1",
    position: 1,
    laps: 57,
    gap: "+0.857s",
    fastestLap: true,
    points: 25,
    editorial:
      "His first Formula 1 victory came in only his second race for Ferrari. He was 21 years old, in the third-best car on the grid, and he made it look inevitable. The final ten laps saw Hamilton close to within a second before backing off, recognising that the young Monégasque wasn't going to be rattled.",
  },
  {
    id: "monza-2019",
    season: 2019,
    round: 14,
    circuit: "Italian Grand Prix",
    country: "Italy",
    flag: "🇮🇹",
    date: "8 September 2019",
    result: "P1",
    position: 1,
    laps: 53,
    gap: "+0.835s",
    fastestLap: false,
    points: 25,
    editorial:
      "The Tifosi had waited four years for this. Charles Leclerc delivered it with the authority of someone who had always intended to. When he crossed the line, sixty thousand people in red stopped being a crowd and became something else entirely.",
  },
  {
    id: "monaco-2024",
    season: 2024,
    round: 8,
    circuit: "Monaco Grand Prix",
    country: "Monaco",
    flag: "🇲🇨",
    date: "26 May 2024",
    result: "P1",
    position: 1,
    laps: 78,
    gap: "+7.152s",
    fastestLap: false,
    points: 25,
    editorial:
      "There will be historians who point to other performances as technically more demanding. They will be wrong about what mattered. On lap 78, when he crossed the line, twenty-seven years of Monaco were finally resolved.",
  },
  {
    id: "singapore-2023",
    season: 2023,
    round: 15,
    circuit: "Singapore Grand Prix",
    country: "Singapore",
    flag: "🇸🇬",
    date: "17 September 2023",
    result: "P1",
    position: 1,
    laps: 62,
    gap: "+1.762s",
    fastestLap: false,
    points: 25,
    editorial:
      "In the wet qualifying session, Charles Leclerc was four-tenths faster than anyone else in conditions where four-tenths is a lifetime. Nobody quite understood where it came from.",
  },
  {
    id: "spain-2022",
    season: 2022,
    round: 6,
    circuit: "Spanish Grand Prix",
    country: "Spain",
    flag: "🇪🇸",
    date: "22 May 2022",
    result: "DNF",
    position: null,
    laps: 27,
    gap: null,
    fastestLap: false,
    points: 0,
    dnfReason: "Engine failure",
    editorial:
      "Lap 27. An engine failure that cost him 25 points and, in retrospect, a World Championship. He had been in a race of his own. He climbed out of the car and drove back to the paddock in silence.",
  },
  {
    id: "monaco-2022",
    season: 2022,
    round: 7,
    circuit: "Monaco Grand Prix",
    country: "Monaco",
    flag: "🇲🇨",
    date: "29 May 2022",
    result: "P4",
    position: 4,
    laps: 78,
    gap: null,
    fastestLap: false,
    points: 12,
    editorial:
      "He led every lap. He did not win. The Monaco Grand Prix, 2022. Charles Leclerc qualified on pole. He led the race from lights to flag — every single lap, for 77 of 78 laps. And then came the pit stop.",
  },
];

export const RADIO_CLIPS: RadioClip[] = [
  {
    id: "bahrain-2019-finish",
    race: "Bahrain Grand Prix",
    season: 2019,
    lap: 57,
    emotion: "JOY",
    engineer: "P1 Charles, P1! Excellent job, excellent job. Well done.",
    charles: "Oh my God, oh my God.",
    durationSecs: 28,
  },
  {
    id: "monza-2019-finish",
    race: "Italian Grand Prix",
    season: 2019,
    lap: 53,
    emotion: "JOY",
    engineer: "Charles, you absolute legend.",
    charles: "Grazie a tutti, grazie a tutti ragazzi. I can't believe it.",
    durationSecs: 35,
  },
  {
    id: "monaco-2024-finish",
    race: "Monaco Grand Prix",
    season: 2024,
    lap: 78,
    emotion: "DISBELIEF",
    engineer: "P1 Charles! P1 Charles! This is for you. This is for Monaco.",
    charles: "For Jules. This one's for Jules.",
    durationSecs: 42,
  },
  {
    id: "spain-2022-dnf",
    race: "Spanish Grand Prix",
    season: 2022,
    lap: 27,
    emotion: "DISAPPOINTMENT",
    engineer: "Box this lap, box this lap.",
    charles: "I have a problem. I have a problem.",
    durationSecs: 20,
  },
  {
    id: "singapore-2023-quali",
    race: "Singapore Qualifying",
    season: 2023,
    lap: 0,
    emotion: "DISBELIEF",
    engineer: "Unbelievable lap Charles, unbelievable. Plus four-tenths to second.",
    charles: "How? Where did I find it?",
    durationSecs: 18,
  },
];

export const PRESS_QUOTES: Quote[] = [
  {
    id: "q1",
    text: "When I'm in the car, nothing else exists. Not the pressure, not the expectations. Just the corner ahead.",
    context: "Post-race press conference · Bahrain 2019",
    year: 2019,
    emotion: "DETERMINED",
  },
  {
    id: "q2",
    text: "Monaco is different. It's always been different. I feel Jules every time I go through the tunnel.",
    context: "Pre-race interview · 2022",
    year: 2022,
    emotion: "REFLECTIVE",
  },
  {
    id: "q3",
    text: "I don't drive to not lose. I drive to win. There's a difference.",
    context: "Paddock interview · 2021",
    year: 2021,
    emotion: "PASSIONATE",
  },
  {
    id: "q4",
    text: "I cried in the car. I don't usually admit that.",
    context: "Post-race · Monaco 2024",
    year: 2024,
    emotion: "HONEST",
  },
  {
    id: "q5",
    text: "The piano and the car require the same thing. Complete silence in here.",
    context: "Feature interview · 2023 — tapping his temple",
    year: 2023,
    emotion: "REFLECTIVE",
  },
  {
    id: "q6",
    text: "If I hadn't met Jules, I think I'd still be racing. But I'm not sure I'd be the same driver.",
    context: "Documentary interview · 2022",
    year: 2022,
    emotion: "REFLECTIVE",
  },
  {
    id: "q7",
    text: "I've never driven like that in my life. I have no idea where it came from.",
    context: "Post-qualifying · Singapore 2023",
    year: 2023,
    emotion: "DISBELIEF",
  },
  {
    id: "q8",
    text: "Losing hurts me. I want it to hurt. The day it doesn't hurt is the day I retire.",
    context: "Post-season interview · 2022",
    year: 2022,
    emotion: "DETERMINED",
  },
  {
    id: "q9",
    text: "When I drove through Monaco as a kid on my way to school, I used to imagine this.",
    context: "Post-race · Monaco 2024",
    year: 2024,
    emotion: "JOY",
  },
];

export const TIERS: TierLevel[] = [
  {
    id: "rookie",
    name: "Rookie",
    icon: "🪖",
    unlock: "Join + complete profile",
    description: "You're new here. Welcome. The races are about to make more sense.",
    privileges: ["Forum access", "Trivia participation"],
    color: "border-white/20",
  },
  {
    id: "tifosi",
    name: "Tifosi",
    icon: "🏎️",
    unlock: "10 correct trivia answers",
    description: "You know your racing. The paddock knows your name.",
    privileges: ["Custom forum badge"],
    color: "border-red",
  },
  {
    id: "pole-sitter",
    name: "Pole Sitter",
    icon: "🥇",
    unlock: "Top 20% weekly trivia score",
    description: "You're not just watching. You're analysing. The data is starting to feel like a language.",
    privileges: ["Early article access", "Gold username"],
    color: "border-gold",
  },
  {
    id: "ferrarista",
    name: "Ferrarista",
    icon: "🐎",
    unlock: "Win a weekly trivia round",
    description: "You've won the weekly trivia. You understand things about Charles Leclerc that his press officers don't.",
    privileges: ["Shop discount", "Exclusive Discord role"],
    color: "border-gold-light",
  },
  {
    id: "leggenda",
    name: "Leggenda",
    icon: "⭐",
    unlock: "3× monthly wins or community contribution",
    description: "You are, at this point, part of the story.",
    privileges: ["All privileges", "Direct recognition"],
    color: "border-gold-light",
  },
];

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: "t1",
    question: "In which lap did Charles Leclerc's engine fail at the 2022 Spanish Grand Prix?",
    options: ["Lap 22", "Lap 27", "Lap 31", "Lap 19"],
    correct: 1,
    category: "Race History",
    explanation: "Charles's SF-75 suffered an internal combustion unit failure on lap 27, ending what had been a dominant race lead.",
  },
  {
    id: "t2",
    question: "What was Charles Leclerc's pole position lap time at Monaco 2021?",
    options: ["1:10.802", "1:10.346", "1:11.123", "1:09.988"],
    correct: 1,
    category: "Qualifying",
    explanation: "1:10.346 — a track record that many said was impossible on that configuration of the Monaco circuit.",
  },
  {
    id: "t3",
    question: "What instrument does Charles Leclerc play?",
    options: ["Guitar", "Violin", "Piano", "Drums"],
    correct: 2,
    category: "Personal",
    explanation: "Charles has played piano since age six and has spoken about the mental parallels between music and motorsport.",
  },
  {
    id: "t4",
    question: "How many laps did Charles lead at the 2022 Monaco GP before the pit stop controversy?",
    options: ["74 laps", "77 laps", "72 laps", "All 78"],
    correct: 1,
    category: "Race History",
    explanation: "Charles led 77 of 78 laps. The controversial undercut pit stop on lap 77 dropped him to fourth.",
  },
  {
    id: "t5",
    question: "At what age did Charles Leclerc first sit in a kart?",
    options: ["Age 6", "Age 4", "Age 5", "Age 7"],
    correct: 1,
    category: "Biography",
    explanation: "Charles first drove a kart aged four at the Cap d'Ail circuit just outside Monaco.",
  },
  {
    id: "t6",
    question: "Which Formula 2 team did Charles drive for in his championship-winning 2017 season?",
    options: ["ART Grand Prix", "PREMA Racing", "Carlin", "MP Motorsport"],
    correct: 1,
    category: "Career",
    explanation: "Charles won the 2017 Formula 2 title with PREMA Racing, a Ferrari-affiliated team.",
  },
  {
    id: "t7",
    question: "Who was Charles Leclerc's racing godfather?",
    options: ["Michael Schumacher", "Kimi Räikkönen", "Jules Bianchi", "Felipe Massa"],
    correct: 2,
    category: "Biography",
    explanation: "Jules Bianchi was Charles's godfather, mentor, and the person who told him he would become World Champion.",
  },
  {
    id: "t8",
    question: "What was Charles Leclerc's points total in the 2022 Formula 1 season?",
    options: ["320 points", "308 points", "290 points", "299 points"],
    correct: 1,
    category: "Season Stats",
    explanation: "Charles scored 308 championship points in 2022, finishing second in the World Championship.",
  },
  {
    id: "t9",
    question: "In which year did Charles Leclerc win his first Formula 1 World Championship?",
    options: ["2022", "2023", "2024", "2025"],
    correct: 2,
    category: "Championships",
    explanation: "Charles Leclerc won the 2024 Formula 1 World Drivers' Championship with Scuderia Ferrari.",
  },
  {
    id: "t10",
    question: "What was Charles Leclerc's car number when he joined Ferrari in 2019?",
    options: ["5", "16", "14", "7"],
    correct: 1,
    category: "Career",
    explanation: "Charles has raced with car number 16 throughout his Formula 1 career, representing his birth month and year in part.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "monaco-2024-tee",
    name: "Monaco 2024 Victory Tee",
    description: "The lap time on the back. The victory on the front. Soft-washed cotton. The unofficial uniform of everyone who was watching.",
    price: 45,
    category: "Clothing",
    isLimited: true,
    limitedTo: 1624,
    badge: "Race Weekend",
  },
  {
    id: "race-suit-replica",
    name: "CL16 Race Suit Replica",
    description: "Ferrari materials. Fan precision. The exact colourway from the 2024 season, scaled for the paddock you actually stand in.",
    price: 185,
    category: "Racing Gear",
  },
  {
    id: "monaco-circuit-print",
    name: "Monaco Circuit Print",
    description: "The circuit that made him wait the longest. Archival inkjet, A2, on 300gsm cotton rag. The lap time annotated at each corner.",
    price: 65,
    category: "Prints & Art",
  },
  {
    id: "helmet-replica-2024",
    name: "Helmet Replica 2024",
    description: "1:2 scale. The exact livery from the Monaco weekend. Hand-finished. Comes with a plinth and a story card.",
    price: 120,
    category: "Racing Gear",
    isLimited: true,
    limitedTo: 500,
    badge: "Limited",
  },
  {
    id: "tifosi-cap",
    name: "Tifosi Cap",
    description: "The paddock staple. One size, one colour, one statement. The embroidered CL16 sits exactly where it should.",
    price: 35,
    category: "Accessories",
  },
];

export const ZONE_CARDS = [
  {
    id: "story",
    name: "The Story",
    tagline: "The man behind the visor",
    description: "From Monaco to Maranello — the full biography.",
    href: "/story",
    circuit: "Bahrain",
    icon: "📖",
  },
  {
    id: "races",
    name: "Race Vault",
    tagline: "Every lap on record",
    description: "Wins, poles, heartbreaks. The complete archive.",
    href: "/races",
    circuit: "Monza",
    icon: "⏱",
  },
  {
    id: "performance",
    name: "Performance Lab",
    tagline: "The data behind the driver",
    description: "Telemetry, pace traces, strategy decoded.",
    href: "/performance",
    circuit: "Silverstone",
    icon: "📊",
  },
  {
    id: "media",
    name: "Media Vault",
    tagline: "See. Hear. Feel.",
    description: "Photography, video, and the radio archive.",
    href: "/media",
    circuit: "Singapore",
    icon: "🎬",
  },
  {
    id: "community",
    name: "Tifosi",
    tagline: "Join the movement",
    description: "Trivia. Leaderboards. Your place in the paddock.",
    href: "/community",
    circuit: "Spa",
    icon: "🏆",
  },
  {
    id: "shop",
    name: "The Store",
    tagline: "Wear the passion",
    description: "Race weekend drops. Limited editions. Fan-curated.",
    href: "/shop",
    circuit: "Maranello",
    icon: "🛍",
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "The Story", href: "/story" },
  { label: "Race Vault", href: "/races" },
  { label: "Performance Lab", href: "/performance" },
  { label: "Media", href: "/media" },
  { label: "Tifosi", href: "/community" },
] as const;
